// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v0/gopherchatter.proto

package gopherchatterv0

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthenticateRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateRequest) Reset()         { *m = AuthenticateRequest{} }
func (m *AuthenticateRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticateRequest) ProtoMessage()    {}
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52cf33cfe78713c, []int{0}
}

func (m *AuthenticateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateRequest.Unmarshal(m, b)
}
func (m *AuthenticateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateRequest.Marshal(b, m, deterministic)
}
func (m *AuthenticateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateRequest.Merge(m, src)
}
func (m *AuthenticateRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticateRequest.Size(m)
}
func (m *AuthenticateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateRequest proto.InternalMessageInfo

func (m *AuthenticateRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthenticateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthenticateResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateResponse) Reset()         { *m = AuthenticateResponse{} }
func (m *AuthenticateResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticateResponse) ProtoMessage()    {}
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52cf33cfe78713c, []int{1}
}

func (m *AuthenticateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateResponse.Unmarshal(m, b)
}
func (m *AuthenticateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateResponse.Marshal(b, m, deterministic)
}
func (m *AuthenticateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateResponse.Merge(m, src)
}
func (m *AuthenticateResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticateResponse.Size(m)
}
func (m *AuthenticateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateResponse proto.InternalMessageInfo

func (m *AuthenticateResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AuthenticateResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthenticateResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type CreateUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52cf33cfe78713c, []int{2}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateGroupChatRequest struct {
	ChatName             string   `protobuf:"bytes,1,opt,name=chat_name,json=chatName,proto3" json:"chat_name,omitempty"`
	CreatorId            string   `protobuf:"bytes,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupChatRequest) Reset()         { *m = CreateGroupChatRequest{} }
func (m *CreateGroupChatRequest) String() string { return proto.CompactTextString(m) }
func (*CreateGroupChatRequest) ProtoMessage()    {}
func (*CreateGroupChatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52cf33cfe78713c, []int{3}
}

func (m *CreateGroupChatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupChatRequest.Unmarshal(m, b)
}
func (m *CreateGroupChatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupChatRequest.Marshal(b, m, deterministic)
}
func (m *CreateGroupChatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupChatRequest.Merge(m, src)
}
func (m *CreateGroupChatRequest) XXX_Size() int {
	return xxx_messageInfo_CreateGroupChatRequest.Size(m)
}
func (m *CreateGroupChatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupChatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupChatRequest proto.InternalMessageInfo

func (m *CreateGroupChatRequest) GetChatName() string {
	if m != nil {
		return m.ChatName
	}
	return ""
}

func (m *CreateGroupChatRequest) GetCreatorId() string {
	if m != nil {
		return m.CreatorId
	}
	return ""
}

type CreateGroupChatResponse struct {
	ChatId               string   `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	ChatName             string   `protobuf:"bytes,2,opt,name=chat_name,json=chatName,proto3" json:"chat_name,omitempty"`
	CreatorId            string   `protobuf:"bytes,3,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	MemberIds            []string `protobuf:"bytes,4,rep,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupChatResponse) Reset()         { *m = CreateGroupChatResponse{} }
func (m *CreateGroupChatResponse) String() string { return proto.CompactTextString(m) }
func (*CreateGroupChatResponse) ProtoMessage()    {}
func (*CreateGroupChatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52cf33cfe78713c, []int{4}
}

func (m *CreateGroupChatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupChatResponse.Unmarshal(m, b)
}
func (m *CreateGroupChatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupChatResponse.Marshal(b, m, deterministic)
}
func (m *CreateGroupChatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupChatResponse.Merge(m, src)
}
func (m *CreateGroupChatResponse) XXX_Size() int {
	return xxx_messageInfo_CreateGroupChatResponse.Size(m)
}
func (m *CreateGroupChatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupChatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupChatResponse proto.InternalMessageInfo

func (m *CreateGroupChatResponse) GetChatId() string {
	if m != nil {
		return m.ChatId
	}
	return ""
}

func (m *CreateGroupChatResponse) GetChatName() string {
	if m != nil {
		return m.ChatName
	}
	return ""
}

func (m *CreateGroupChatResponse) GetCreatorId() string {
	if m != nil {
		return m.CreatorId
	}
	return ""
}

func (m *CreateGroupChatResponse) GetMemberIds() []string {
	if m != nil {
		return m.MemberIds
	}
	return nil
}

type AddContactToGroupChatRequest struct {
	ChatId               string   `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	CreatorId            string   `protobuf:"bytes,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	ContactId            string   `protobuf:"bytes,3,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddContactToGroupChatRequest) Reset()         { *m = AddContactToGroupChatRequest{} }
func (m *AddContactToGroupChatRequest) String() string { return proto.CompactTextString(m) }
func (*AddContactToGroupChatRequest) ProtoMessage()    {}
func (*AddContactToGroupChatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52cf33cfe78713c, []int{5}
}

func (m *AddContactToGroupChatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddContactToGroupChatRequest.Unmarshal(m, b)
}
func (m *AddContactToGroupChatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddContactToGroupChatRequest.Marshal(b, m, deterministic)
}
func (m *AddContactToGroupChatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddContactToGroupChatRequest.Merge(m, src)
}
func (m *AddContactToGroupChatRequest) XXX_Size() int {
	return xxx_messageInfo_AddContactToGroupChatRequest.Size(m)
}
func (m *AddContactToGroupChatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddContactToGroupChatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddContactToGroupChatRequest proto.InternalMessageInfo

func (m *AddContactToGroupChatRequest) GetChatId() string {
	if m != nil {
		return m.ChatId
	}
	return ""
}

func (m *AddContactToGroupChatRequest) GetCreatorId() string {
	if m != nil {
		return m.CreatorId
	}
	return ""
}

func (m *AddContactToGroupChatRequest) GetContactId() string {
	if m != nil {
		return m.ContactId
	}
	return ""
}

type RemoveUserFromGroupChatRequest struct {
	ChatId               string   `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	CreatorId            string   `protobuf:"bytes,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	ContactId            string   `protobuf:"bytes,3,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveUserFromGroupChatRequest) Reset()         { *m = RemoveUserFromGroupChatRequest{} }
func (m *RemoveUserFromGroupChatRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveUserFromGroupChatRequest) ProtoMessage()    {}
func (*RemoveUserFromGroupChatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52cf33cfe78713c, []int{6}
}

func (m *RemoveUserFromGroupChatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveUserFromGroupChatRequest.Unmarshal(m, b)
}
func (m *RemoveUserFromGroupChatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveUserFromGroupChatRequest.Marshal(b, m, deterministic)
}
func (m *RemoveUserFromGroupChatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveUserFromGroupChatRequest.Merge(m, src)
}
func (m *RemoveUserFromGroupChatRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveUserFromGroupChatRequest.Size(m)
}
func (m *RemoveUserFromGroupChatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveUserFromGroupChatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveUserFromGroupChatRequest proto.InternalMessageInfo

func (m *RemoveUserFromGroupChatRequest) GetChatId() string {
	if m != nil {
		return m.ChatId
	}
	return ""
}

func (m *RemoveUserFromGroupChatRequest) GetCreatorId() string {
	if m != nil {
		return m.CreatorId
	}
	return ""
}

func (m *RemoveUserFromGroupChatRequest) GetContactId() string {
	if m != nil {
		return m.ContactId
	}
	return ""
}

type AddContactRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ContactId            string   `protobuf:"bytes,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddContactRequest) Reset()         { *m = AddContactRequest{} }
func (m *AddContactRequest) String() string { return proto.CompactTextString(m) }
func (*AddContactRequest) ProtoMessage()    {}
func (*AddContactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52cf33cfe78713c, []int{7}
}

func (m *AddContactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddContactRequest.Unmarshal(m, b)
}
func (m *AddContactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddContactRequest.Marshal(b, m, deterministic)
}
func (m *AddContactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddContactRequest.Merge(m, src)
}
func (m *AddContactRequest) XXX_Size() int {
	return xxx_messageInfo_AddContactRequest.Size(m)
}
func (m *AddContactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddContactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddContactRequest proto.InternalMessageInfo

func (m *AddContactRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AddContactRequest) GetContactId() string {
	if m != nil {
		return m.ContactId
	}
	return ""
}

type RemoveContactRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ContactId            string   `protobuf:"bytes,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveContactRequest) Reset()         { *m = RemoveContactRequest{} }
func (m *RemoveContactRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveContactRequest) ProtoMessage()    {}
func (*RemoveContactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52cf33cfe78713c, []int{8}
}

func (m *RemoveContactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveContactRequest.Unmarshal(m, b)
}
func (m *RemoveContactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveContactRequest.Marshal(b, m, deterministic)
}
func (m *RemoveContactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveContactRequest.Merge(m, src)
}
func (m *RemoveContactRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveContactRequest.Size(m)
}
func (m *RemoveContactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveContactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveContactRequest proto.InternalMessageInfo

func (m *RemoveContactRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RemoveContactRequest) GetContactId() string {
	if m != nil {
		return m.ContactId
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthenticateRequest)(nil), "gopherchatter.v0.AuthenticateRequest")
	proto.RegisterType((*AuthenticateResponse)(nil), "gopherchatter.v0.AuthenticateResponse")
	proto.RegisterType((*CreateUserRequest)(nil), "gopherchatter.v0.CreateUserRequest")
	proto.RegisterType((*CreateGroupChatRequest)(nil), "gopherchatter.v0.CreateGroupChatRequest")
	proto.RegisterType((*CreateGroupChatResponse)(nil), "gopherchatter.v0.CreateGroupChatResponse")
	proto.RegisterType((*AddContactToGroupChatRequest)(nil), "gopherchatter.v0.AddContactToGroupChatRequest")
	proto.RegisterType((*RemoveUserFromGroupChatRequest)(nil), "gopherchatter.v0.RemoveUserFromGroupChatRequest")
	proto.RegisterType((*AddContactRequest)(nil), "gopherchatter.v0.AddContactRequest")
	proto.RegisterType((*RemoveContactRequest)(nil), "gopherchatter.v0.RemoveContactRequest")
}

func init() { proto.RegisterFile("v0/gopherchatter.proto", fileDescriptor_f52cf33cfe78713c) }

var fileDescriptor_f52cf33cfe78713c = []byte{
	// 490 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0xdf, 0x6b, 0x13, 0x41,
	0x10, 0xc7, 0x49, 0x62, 0xab, 0x19, 0x2c, 0x35, 0x6b, 0x4c, 0xc2, 0x55, 0xa5, 0x9c, 0x58, 0xea,
	0xcb, 0x25, 0xe8, 0x5f, 0x50, 0x83, 0x96, 0xa3, 0x58, 0x21, 0xd4, 0x17, 0x41, 0xc2, 0xe6, 0x76,
	0x9a, 0x14, 0xbd, 0xdb, 0x73, 0x77, 0x2f, 0xc5, 0x67, 0x9f, 0xfd, 0x9f, 0x65, 0x77, 0x13, 0xef,
	0xf7, 0x19, 0x50, 0xfa, 0x38, 0x33, 0xbb, 0x9f, 0xf9, 0xb1, 0xdf, 0x59, 0x18, 0xac, 0x27, 0xe3,
	0x25, 0x8f, 0x57, 0x28, 0x82, 0x15, 0x55, 0x0a, 0x85, 0x17, 0x0b, 0xae, 0x38, 0x79, 0x94, 0x77,
	0xae, 0x27, 0xce, 0xd1, 0x92, 0xf3, 0xe5, 0x37, 0x1c, 0x9b, 0xf8, 0x22, 0xb9, 0x1e, 0x63, 0x18,
	0xab, 0x1f, 0xf6, 0xb8, 0xfb, 0x01, 0x1e, 0x9f, 0x25, 0x6a, 0x85, 0x91, 0xba, 0x09, 0xa8, 0xc2,
	0x19, 0x7e, 0x4f, 0x50, 0x2a, 0xe2, 0xc0, 0x83, 0x44, 0xa2, 0x88, 0x68, 0x88, 0xa3, 0xd6, 0x71,
	0xeb, 0xb4, 0x3b, 0xfb, 0x63, 0xeb, 0x58, 0x4c, 0xa5, 0xbc, 0xe5, 0x82, 0x8d, 0xda, 0x36, 0xb6,
	0xb5, 0x5d, 0x0a, 0xfd, 0x3c, 0x4e, 0xc6, 0x3c, 0x92, 0x48, 0x86, 0x70, 0x5f, 0xdf, 0x9f, 0xdf,
	0xb0, 0x0d, 0x6e, 0x5f, 0x9b, 0x3e, 0xcb, 0x25, 0x6a, 0x17, 0x12, 0xf5, 0x61, 0x4f, 0xf1, 0xaf,
	0x18, 0x8d, 0x3a, 0x26, 0x60, 0x0d, 0xf7, 0x02, 0x7a, 0x53, 0x81, 0x54, 0xe1, 0x27, 0x89, 0xe2,
	0x5f, 0xeb, 0xbd, 0x82, 0x81, 0x85, 0x9d, 0x0b, 0x9e, 0xc4, 0xd3, 0x15, 0x55, 0x5b, 0xe2, 0x11,
	0x74, 0xf5, 0x0c, 0xe7, 0x59, 0xa4, 0x76, 0x5c, 0x6a, 0xe4, 0x33, 0x80, 0x40, 0x5f, 0xe3, 0xa6,
	0x23, 0x0b, 0xed, 0x6e, 0x3c, 0x3e, 0x73, 0x7f, 0xb5, 0x60, 0x58, 0xc2, 0xa6, 0x93, 0x30, 0xdc,
	0x74, 0x12, 0xda, 0xf4, 0x59, 0x3e, 0x61, 0xbb, 0x31, 0x61, 0xa7, 0x90, 0x50, 0x87, 0x43, 0x0c,
	0x17, 0x66, 0xc0, 0x72, 0x74, 0xef, 0xb8, 0xa3, 0xc3, 0xd6, 0xe3, 0x33, 0xe9, 0x26, 0xf0, 0xf4,
	0x8c, 0xb1, 0x29, 0x8f, 0x14, 0x0d, 0xd4, 0x15, 0x2f, 0xf5, 0x5a, 0x5b, 0x53, 0x73, 0x9f, 0x26,
	0x6c, 0xa1, 0xd9, 0xaa, 0xac, 0xc7, 0x67, 0xee, 0x2d, 0x3c, 0x9f, 0x61, 0xc8, 0xd7, 0xe6, 0xa5,
	0xde, 0x0b, 0x1e, 0xde, 0x55, 0xe2, 0x0b, 0xe8, 0xa5, 0xfd, 0x66, 0x72, 0x55, 0x4b, 0x30, 0x0f,
	0x6b, 0x17, 0x61, 0x97, 0xd0, 0xb7, 0x5d, 0xfc, 0x1f, 0xde, 0xeb, 0x9f, 0x7b, 0x70, 0x70, 0x6e,
	0x76, 0x74, 0x6a, 0x77, 0x94, 0x7c, 0x81, 0x87, 0xd9, 0xa5, 0x21, 0x2f, 0xbd, 0xe2, 0x0e, 0x7b,
	0x15, 0x3b, 0xea, 0x9c, 0xfc, 0xed, 0xd8, 0x46, 0x71, 0x3e, 0x40, 0xba, 0x30, 0xe4, 0x45, 0xf9,
	0x56, 0x69, 0x9d, 0x9c, 0x81, 0x67, 0xff, 0x0c, 0x6f, 0xfb, 0x67, 0x78, 0xef, 0xf4, 0x9f, 0x41,
	0xae, 0xe1, 0xb0, 0xa0, 0x6b, 0x72, 0x5a, 0xc7, 0x2b, 0x3e, 0xb6, 0xf3, 0x6a, 0x87, 0x93, 0x9b,
	0x92, 0xe7, 0xf0, 0xa4, 0x52, 0xb0, 0xc4, 0xab, 0xe8, 0xb9, 0x41, 0xd9, 0xb5, 0x8d, 0x04, 0x30,
	0xac, 0x91, 0x26, 0x99, 0x94, 0x53, 0x34, 0xab, 0xb8, 0x36, 0x89, 0x0f, 0x90, 0x16, 0x57, 0x35,
	0xf8, 0x92, 0x48, 0x6b, 0x51, 0x1f, 0xe1, 0x20, 0x27, 0x42, 0x72, 0x52, 0x57, 0xe5, 0x6e, 0xc0,
	0xb7, 0xbd, 0xcf, 0x87, 0x39, 0xc0, 0x7a, 0xb2, 0xd8, 0x37, 0x47, 0xde, 0xfc, 0x0e, 0x00, 0x00,
	0xff, 0xff, 0x7b, 0x0b, 0xc2, 0x40, 0x5a, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GopherChatterClient is the client API for GopherChatter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GopherChatterClient interface {
	Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	CreateGroupChat(ctx context.Context, in *CreateGroupChatRequest, opts ...grpc.CallOption) (*CreateGroupChatResponse, error)
	AddContactToGroupChat(ctx context.Context, in *AddContactToGroupChatRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	RemoveUserFromGroupChat(ctx context.Context, in *RemoveUserFromGroupChatRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	AddContact(ctx context.Context, in *AddContactRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	RemoveContact(ctx context.Context, in *RemoveContactRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type gopherChatterClient struct {
	cc *grpc.ClientConn
}

func NewGopherChatterClient(cc *grpc.ClientConn) GopherChatterClient {
	return &gopherChatterClient{cc}
}

func (c *gopherChatterClient) Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	out := new(AuthenticateResponse)
	err := c.cc.Invoke(ctx, "/gopherchatter.v0.GopherChatter/Authenticate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopherChatterClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/gopherchatter.v0.GopherChatter/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopherChatterClient) CreateGroupChat(ctx context.Context, in *CreateGroupChatRequest, opts ...grpc.CallOption) (*CreateGroupChatResponse, error) {
	out := new(CreateGroupChatResponse)
	err := c.cc.Invoke(ctx, "/gopherchatter.v0.GopherChatter/CreateGroupChat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopherChatterClient) AddContactToGroupChat(ctx context.Context, in *AddContactToGroupChatRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/gopherchatter.v0.GopherChatter/AddContactToGroupChat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopherChatterClient) RemoveUserFromGroupChat(ctx context.Context, in *RemoveUserFromGroupChatRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/gopherchatter.v0.GopherChatter/RemoveUserFromGroupChat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopherChatterClient) AddContact(ctx context.Context, in *AddContactRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/gopherchatter.v0.GopherChatter/AddContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopherChatterClient) RemoveContact(ctx context.Context, in *RemoveContactRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/gopherchatter.v0.GopherChatter/RemoveContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GopherChatterServer is the server API for GopherChatter service.
type GopherChatterServer interface {
	Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error)
	CreateUser(context.Context, *CreateUserRequest) (*empty.Empty, error)
	CreateGroupChat(context.Context, *CreateGroupChatRequest) (*CreateGroupChatResponse, error)
	AddContactToGroupChat(context.Context, *AddContactToGroupChatRequest) (*empty.Empty, error)
	RemoveUserFromGroupChat(context.Context, *RemoveUserFromGroupChatRequest) (*empty.Empty, error)
	AddContact(context.Context, *AddContactRequest) (*empty.Empty, error)
	RemoveContact(context.Context, *RemoveContactRequest) (*empty.Empty, error)
}

// UnimplementedGopherChatterServer can be embedded to have forward compatible implementations.
type UnimplementedGopherChatterServer struct {
}

func (*UnimplementedGopherChatterServer) Authenticate(ctx context.Context, req *AuthenticateRequest) (*AuthenticateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}
func (*UnimplementedGopherChatterServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedGopherChatterServer) CreateGroupChat(ctx context.Context, req *CreateGroupChatRequest) (*CreateGroupChatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGroupChat not implemented")
}
func (*UnimplementedGopherChatterServer) AddContactToGroupChat(ctx context.Context, req *AddContactToGroupChatRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddContactToGroupChat not implemented")
}
func (*UnimplementedGopherChatterServer) RemoveUserFromGroupChat(ctx context.Context, req *RemoveUserFromGroupChatRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveUserFromGroupChat not implemented")
}
func (*UnimplementedGopherChatterServer) AddContact(ctx context.Context, req *AddContactRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddContact not implemented")
}
func (*UnimplementedGopherChatterServer) RemoveContact(ctx context.Context, req *RemoveContactRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveContact not implemented")
}

func RegisterGopherChatterServer(s *grpc.Server, srv GopherChatterServer) {
	s.RegisterService(&_GopherChatter_serviceDesc, srv)
}

func _GopherChatter_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopherChatterServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopherchatter.v0.GopherChatter/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopherChatterServer).Authenticate(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopherChatter_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopherChatterServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopherchatter.v0.GopherChatter/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopherChatterServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopherChatter_CreateGroupChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopherChatterServer).CreateGroupChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopherchatter.v0.GopherChatter/CreateGroupChat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopherChatterServer).CreateGroupChat(ctx, req.(*CreateGroupChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopherChatter_AddContactToGroupChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddContactToGroupChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopherChatterServer).AddContactToGroupChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopherchatter.v0.GopherChatter/AddContactToGroupChat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopherChatterServer).AddContactToGroupChat(ctx, req.(*AddContactToGroupChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopherChatter_RemoveUserFromGroupChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveUserFromGroupChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopherChatterServer).RemoveUserFromGroupChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopherchatter.v0.GopherChatter/RemoveUserFromGroupChat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopherChatterServer).RemoveUserFromGroupChat(ctx, req.(*RemoveUserFromGroupChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopherChatter_AddContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopherChatterServer).AddContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopherchatter.v0.GopherChatter/AddContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopherChatterServer).AddContact(ctx, req.(*AddContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopherChatter_RemoveContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopherChatterServer).RemoveContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopherchatter.v0.GopherChatter/RemoveContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopherChatterServer).RemoveContact(ctx, req.(*RemoveContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GopherChatter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gopherchatter.v0.GopherChatter",
	HandlerType: (*GopherChatterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _GopherChatter_Authenticate_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _GopherChatter_CreateUser_Handler,
		},
		{
			MethodName: "CreateGroupChat",
			Handler:    _GopherChatter_CreateGroupChat_Handler,
		},
		{
			MethodName: "AddContactToGroupChat",
			Handler:    _GopherChatter_AddContactToGroupChat_Handler,
		},
		{
			MethodName: "RemoveUserFromGroupChat",
			Handler:    _GopherChatter_RemoveUserFromGroupChat_Handler,
		},
		{
			MethodName: "AddContact",
			Handler:    _GopherChatter_AddContact_Handler,
		},
		{
			MethodName: "RemoveContact",
			Handler:    _GopherChatter_RemoveContact_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v0/gopherchatter.proto",
}
