// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v0/gopherchatter.proto

package gopherchatterv0

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Contact struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Contact) Reset()         { *m = Contact{} }
func (m *Contact) String() string { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()    {}
func (*Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52cf33cfe78713c, []int{0}
}

func (m *Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contact.Unmarshal(m, b)
}
func (m *Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contact.Marshal(b, m, deterministic)
}
func (m *Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contact.Merge(m, src)
}
func (m *Contact) XXX_Size() int {
	return xxx_messageInfo_Contact.Size(m)
}
func (m *Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_Contact proto.InternalMessageInfo

func (m *Contact) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Contact) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type AuthenticateRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateRequest) Reset()         { *m = AuthenticateRequest{} }
func (m *AuthenticateRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticateRequest) ProtoMessage()    {}
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52cf33cfe78713c, []int{1}
}

func (m *AuthenticateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateRequest.Unmarshal(m, b)
}
func (m *AuthenticateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateRequest.Marshal(b, m, deterministic)
}
func (m *AuthenticateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateRequest.Merge(m, src)
}
func (m *AuthenticateRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticateRequest.Size(m)
}
func (m *AuthenticateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateRequest proto.InternalMessageInfo

func (m *AuthenticateRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthenticateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthenticateResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateResponse) Reset()         { *m = AuthenticateResponse{} }
func (m *AuthenticateResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticateResponse) ProtoMessage()    {}
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52cf33cfe78713c, []int{2}
}

func (m *AuthenticateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateResponse.Unmarshal(m, b)
}
func (m *AuthenticateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateResponse.Marshal(b, m, deterministic)
}
func (m *AuthenticateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateResponse.Merge(m, src)
}
func (m *AuthenticateResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticateResponse.Size(m)
}
func (m *AuthenticateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateResponse proto.InternalMessageInfo

func (m *AuthenticateResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AuthenticateResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthenticateResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type CreateUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52cf33cfe78713c, []int{3}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateIndividualChatRequest struct {
	WithUserId           string   `protobuf:"bytes,1,opt,name=with_user_id,json=withUserId,proto3" json:"with_user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateIndividualChatRequest) Reset()         { *m = CreateIndividualChatRequest{} }
func (m *CreateIndividualChatRequest) String() string { return proto.CompactTextString(m) }
func (*CreateIndividualChatRequest) ProtoMessage()    {}
func (*CreateIndividualChatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52cf33cfe78713c, []int{4}
}

func (m *CreateIndividualChatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateIndividualChatRequest.Unmarshal(m, b)
}
func (m *CreateIndividualChatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateIndividualChatRequest.Marshal(b, m, deterministic)
}
func (m *CreateIndividualChatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateIndividualChatRequest.Merge(m, src)
}
func (m *CreateIndividualChatRequest) XXX_Size() int {
	return xxx_messageInfo_CreateIndividualChatRequest.Size(m)
}
func (m *CreateIndividualChatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateIndividualChatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateIndividualChatRequest proto.InternalMessageInfo

func (m *CreateIndividualChatRequest) GetWithUserId() string {
	if m != nil {
		return m.WithUserId
	}
	return ""
}

type CreateIndividualChatResponse struct {
	ChatId               string   `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	MemberIds            []string `protobuf:"bytes,2,rep,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateIndividualChatResponse) Reset()         { *m = CreateIndividualChatResponse{} }
func (m *CreateIndividualChatResponse) String() string { return proto.CompactTextString(m) }
func (*CreateIndividualChatResponse) ProtoMessage()    {}
func (*CreateIndividualChatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52cf33cfe78713c, []int{5}
}

func (m *CreateIndividualChatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateIndividualChatResponse.Unmarshal(m, b)
}
func (m *CreateIndividualChatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateIndividualChatResponse.Marshal(b, m, deterministic)
}
func (m *CreateIndividualChatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateIndividualChatResponse.Merge(m, src)
}
func (m *CreateIndividualChatResponse) XXX_Size() int {
	return xxx_messageInfo_CreateIndividualChatResponse.Size(m)
}
func (m *CreateIndividualChatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateIndividualChatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateIndividualChatResponse proto.InternalMessageInfo

func (m *CreateIndividualChatResponse) GetChatId() string {
	if m != nil {
		return m.ChatId
	}
	return ""
}

func (m *CreateIndividualChatResponse) GetMemberIds() []string {
	if m != nil {
		return m.MemberIds
	}
	return nil
}

type GetIndividualChatsRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIndividualChatsRequest) Reset()         { *m = GetIndividualChatsRequest{} }
func (m *GetIndividualChatsRequest) String() string { return proto.CompactTextString(m) }
func (*GetIndividualChatsRequest) ProtoMessage()    {}
func (*GetIndividualChatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52cf33cfe78713c, []int{6}
}

func (m *GetIndividualChatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIndividualChatsRequest.Unmarshal(m, b)
}
func (m *GetIndividualChatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIndividualChatsRequest.Marshal(b, m, deterministic)
}
func (m *GetIndividualChatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIndividualChatsRequest.Merge(m, src)
}
func (m *GetIndividualChatsRequest) XXX_Size() int {
	return xxx_messageInfo_GetIndividualChatsRequest.Size(m)
}
func (m *GetIndividualChatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIndividualChatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetIndividualChatsRequest proto.InternalMessageInfo

func (m *GetIndividualChatsRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetIndividualChatsResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChatIds              []string `protobuf:"bytes,2,rep,name=chat_ids,json=chatIds,proto3" json:"chat_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIndividualChatsResponse) Reset()         { *m = GetIndividualChatsResponse{} }
func (m *GetIndividualChatsResponse) String() string { return proto.CompactTextString(m) }
func (*GetIndividualChatsResponse) ProtoMessage()    {}
func (*GetIndividualChatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52cf33cfe78713c, []int{7}
}

func (m *GetIndividualChatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIndividualChatsResponse.Unmarshal(m, b)
}
func (m *GetIndividualChatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIndividualChatsResponse.Marshal(b, m, deterministic)
}
func (m *GetIndividualChatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIndividualChatsResponse.Merge(m, src)
}
func (m *GetIndividualChatsResponse) XXX_Size() int {
	return xxx_messageInfo_GetIndividualChatsResponse.Size(m)
}
func (m *GetIndividualChatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIndividualChatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetIndividualChatsResponse proto.InternalMessageInfo

func (m *GetIndividualChatsResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetIndividualChatsResponse) GetChatIds() []string {
	if m != nil {
		return m.ChatIds
	}
	return nil
}

type CreateGroupChatRequest struct {
	ChatName             string   `protobuf:"bytes,1,opt,name=chat_name,json=chatName,proto3" json:"chat_name,omitempty"`
	AdminId              string   `protobuf:"bytes,2,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupChatRequest) Reset()         { *m = CreateGroupChatRequest{} }
func (m *CreateGroupChatRequest) String() string { return proto.CompactTextString(m) }
func (*CreateGroupChatRequest) ProtoMessage()    {}
func (*CreateGroupChatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52cf33cfe78713c, []int{8}
}

func (m *CreateGroupChatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupChatRequest.Unmarshal(m, b)
}
func (m *CreateGroupChatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupChatRequest.Marshal(b, m, deterministic)
}
func (m *CreateGroupChatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupChatRequest.Merge(m, src)
}
func (m *CreateGroupChatRequest) XXX_Size() int {
	return xxx_messageInfo_CreateGroupChatRequest.Size(m)
}
func (m *CreateGroupChatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupChatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupChatRequest proto.InternalMessageInfo

func (m *CreateGroupChatRequest) GetChatName() string {
	if m != nil {
		return m.ChatName
	}
	return ""
}

func (m *CreateGroupChatRequest) GetAdminId() string {
	if m != nil {
		return m.AdminId
	}
	return ""
}

type CreateGroupChatResponse struct {
	ChatId               string   `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	ChatName             string   `protobuf:"bytes,2,opt,name=chat_name,json=chatName,proto3" json:"chat_name,omitempty"`
	AdminId              string   `protobuf:"bytes,3,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	MemberIds            []string `protobuf:"bytes,4,rep,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupChatResponse) Reset()         { *m = CreateGroupChatResponse{} }
func (m *CreateGroupChatResponse) String() string { return proto.CompactTextString(m) }
func (*CreateGroupChatResponse) ProtoMessage()    {}
func (*CreateGroupChatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52cf33cfe78713c, []int{9}
}

func (m *CreateGroupChatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupChatResponse.Unmarshal(m, b)
}
func (m *CreateGroupChatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupChatResponse.Marshal(b, m, deterministic)
}
func (m *CreateGroupChatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupChatResponse.Merge(m, src)
}
func (m *CreateGroupChatResponse) XXX_Size() int {
	return xxx_messageInfo_CreateGroupChatResponse.Size(m)
}
func (m *CreateGroupChatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupChatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupChatResponse proto.InternalMessageInfo

func (m *CreateGroupChatResponse) GetChatId() string {
	if m != nil {
		return m.ChatId
	}
	return ""
}

func (m *CreateGroupChatResponse) GetChatName() string {
	if m != nil {
		return m.ChatName
	}
	return ""
}

func (m *CreateGroupChatResponse) GetAdminId() string {
	if m != nil {
		return m.AdminId
	}
	return ""
}

func (m *CreateGroupChatResponse) GetMemberIds() []string {
	if m != nil {
		return m.MemberIds
	}
	return nil
}

type GetGroupChatsRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupChatsRequest) Reset()         { *m = GetGroupChatsRequest{} }
func (m *GetGroupChatsRequest) String() string { return proto.CompactTextString(m) }
func (*GetGroupChatsRequest) ProtoMessage()    {}
func (*GetGroupChatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52cf33cfe78713c, []int{10}
}

func (m *GetGroupChatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupChatsRequest.Unmarshal(m, b)
}
func (m *GetGroupChatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupChatsRequest.Marshal(b, m, deterministic)
}
func (m *GetGroupChatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupChatsRequest.Merge(m, src)
}
func (m *GetGroupChatsRequest) XXX_Size() int {
	return xxx_messageInfo_GetGroupChatsRequest.Size(m)
}
func (m *GetGroupChatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupChatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupChatsRequest proto.InternalMessageInfo

func (m *GetGroupChatsRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetGroupChatsResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChatIds              []string `protobuf:"bytes,2,rep,name=chat_ids,json=chatIds,proto3" json:"chat_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupChatsResponse) Reset()         { *m = GetGroupChatsResponse{} }
func (m *GetGroupChatsResponse) String() string { return proto.CompactTextString(m) }
func (*GetGroupChatsResponse) ProtoMessage()    {}
func (*GetGroupChatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52cf33cfe78713c, []int{11}
}

func (m *GetGroupChatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupChatsResponse.Unmarshal(m, b)
}
func (m *GetGroupChatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupChatsResponse.Marshal(b, m, deterministic)
}
func (m *GetGroupChatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupChatsResponse.Merge(m, src)
}
func (m *GetGroupChatsResponse) XXX_Size() int {
	return xxx_messageInfo_GetGroupChatsResponse.Size(m)
}
func (m *GetGroupChatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupChatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupChatsResponse proto.InternalMessageInfo

func (m *GetGroupChatsResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetGroupChatsResponse) GetChatIds() []string {
	if m != nil {
		return m.ChatIds
	}
	return nil
}

type AddContactToGroupChatRequest struct {
	ChatId               string   `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	AdminId              string   `protobuf:"bytes,2,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	ContactId            string   `protobuf:"bytes,3,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddContactToGroupChatRequest) Reset()         { *m = AddContactToGroupChatRequest{} }
func (m *AddContactToGroupChatRequest) String() string { return proto.CompactTextString(m) }
func (*AddContactToGroupChatRequest) ProtoMessage()    {}
func (*AddContactToGroupChatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52cf33cfe78713c, []int{12}
}

func (m *AddContactToGroupChatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddContactToGroupChatRequest.Unmarshal(m, b)
}
func (m *AddContactToGroupChatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddContactToGroupChatRequest.Marshal(b, m, deterministic)
}
func (m *AddContactToGroupChatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddContactToGroupChatRequest.Merge(m, src)
}
func (m *AddContactToGroupChatRequest) XXX_Size() int {
	return xxx_messageInfo_AddContactToGroupChatRequest.Size(m)
}
func (m *AddContactToGroupChatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddContactToGroupChatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddContactToGroupChatRequest proto.InternalMessageInfo

func (m *AddContactToGroupChatRequest) GetChatId() string {
	if m != nil {
		return m.ChatId
	}
	return ""
}

func (m *AddContactToGroupChatRequest) GetAdminId() string {
	if m != nil {
		return m.AdminId
	}
	return ""
}

func (m *AddContactToGroupChatRequest) GetContactId() string {
	if m != nil {
		return m.ContactId
	}
	return ""
}

type RemoveContactFromGroupChatRequest struct {
	ChatId               string   `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	AdminId              string   `protobuf:"bytes,2,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	ContactId            string   `protobuf:"bytes,3,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveContactFromGroupChatRequest) Reset()         { *m = RemoveContactFromGroupChatRequest{} }
func (m *RemoveContactFromGroupChatRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveContactFromGroupChatRequest) ProtoMessage()    {}
func (*RemoveContactFromGroupChatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52cf33cfe78713c, []int{13}
}

func (m *RemoveContactFromGroupChatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveContactFromGroupChatRequest.Unmarshal(m, b)
}
func (m *RemoveContactFromGroupChatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveContactFromGroupChatRequest.Marshal(b, m, deterministic)
}
func (m *RemoveContactFromGroupChatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveContactFromGroupChatRequest.Merge(m, src)
}
func (m *RemoveContactFromGroupChatRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveContactFromGroupChatRequest.Size(m)
}
func (m *RemoveContactFromGroupChatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveContactFromGroupChatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveContactFromGroupChatRequest proto.InternalMessageInfo

func (m *RemoveContactFromGroupChatRequest) GetChatId() string {
	if m != nil {
		return m.ChatId
	}
	return ""
}

func (m *RemoveContactFromGroupChatRequest) GetAdminId() string {
	if m != nil {
		return m.AdminId
	}
	return ""
}

func (m *RemoveContactFromGroupChatRequest) GetContactId() string {
	if m != nil {
		return m.ContactId
	}
	return ""
}

type SendMessageToIndividualChatRequest struct {
	ChatId               string   `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	AuthorId             string   `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageToIndividualChatRequest) Reset()         { *m = SendMessageToIndividualChatRequest{} }
func (m *SendMessageToIndividualChatRequest) String() string { return proto.CompactTextString(m) }
func (*SendMessageToIndividualChatRequest) ProtoMessage()    {}
func (*SendMessageToIndividualChatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52cf33cfe78713c, []int{14}
}

func (m *SendMessageToIndividualChatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageToIndividualChatRequest.Unmarshal(m, b)
}
func (m *SendMessageToIndividualChatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageToIndividualChatRequest.Marshal(b, m, deterministic)
}
func (m *SendMessageToIndividualChatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageToIndividualChatRequest.Merge(m, src)
}
func (m *SendMessageToIndividualChatRequest) XXX_Size() int {
	return xxx_messageInfo_SendMessageToIndividualChatRequest.Size(m)
}
func (m *SendMessageToIndividualChatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageToIndividualChatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageToIndividualChatRequest proto.InternalMessageInfo

func (m *SendMessageToIndividualChatRequest) GetChatId() string {
	if m != nil {
		return m.ChatId
	}
	return ""
}

func (m *SendMessageToIndividualChatRequest) GetAuthorId() string {
	if m != nil {
		return m.AuthorId
	}
	return ""
}

func (m *SendMessageToIndividualChatRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type SendMessageToIndividualChatResponse struct {
	MessageId            string   `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ChatId               string   `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	AuthorId             string   `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageToIndividualChatResponse) Reset()         { *m = SendMessageToIndividualChatResponse{} }
func (m *SendMessageToIndividualChatResponse) String() string { return proto.CompactTextString(m) }
func (*SendMessageToIndividualChatResponse) ProtoMessage()    {}
func (*SendMessageToIndividualChatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52cf33cfe78713c, []int{15}
}

func (m *SendMessageToIndividualChatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageToIndividualChatResponse.Unmarshal(m, b)
}
func (m *SendMessageToIndividualChatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageToIndividualChatResponse.Marshal(b, m, deterministic)
}
func (m *SendMessageToIndividualChatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageToIndividualChatResponse.Merge(m, src)
}
func (m *SendMessageToIndividualChatResponse) XXX_Size() int {
	return xxx_messageInfo_SendMessageToIndividualChatResponse.Size(m)
}
func (m *SendMessageToIndividualChatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageToIndividualChatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageToIndividualChatResponse proto.InternalMessageInfo

func (m *SendMessageToIndividualChatResponse) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *SendMessageToIndividualChatResponse) GetChatId() string {
	if m != nil {
		return m.ChatId
	}
	return ""
}

func (m *SendMessageToIndividualChatResponse) GetAuthorId() string {
	if m != nil {
		return m.AuthorId
	}
	return ""
}

func (m *SendMessageToIndividualChatResponse) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type SendMessageToGroupChatRequest struct {
	ChatId               string   `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	AuthorId             string   `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageToGroupChatRequest) Reset()         { *m = SendMessageToGroupChatRequest{} }
func (m *SendMessageToGroupChatRequest) String() string { return proto.CompactTextString(m) }
func (*SendMessageToGroupChatRequest) ProtoMessage()    {}
func (*SendMessageToGroupChatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52cf33cfe78713c, []int{16}
}

func (m *SendMessageToGroupChatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageToGroupChatRequest.Unmarshal(m, b)
}
func (m *SendMessageToGroupChatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageToGroupChatRequest.Marshal(b, m, deterministic)
}
func (m *SendMessageToGroupChatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageToGroupChatRequest.Merge(m, src)
}
func (m *SendMessageToGroupChatRequest) XXX_Size() int {
	return xxx_messageInfo_SendMessageToGroupChatRequest.Size(m)
}
func (m *SendMessageToGroupChatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageToGroupChatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageToGroupChatRequest proto.InternalMessageInfo

func (m *SendMessageToGroupChatRequest) GetChatId() string {
	if m != nil {
		return m.ChatId
	}
	return ""
}

func (m *SendMessageToGroupChatRequest) GetAuthorId() string {
	if m != nil {
		return m.AuthorId
	}
	return ""
}

func (m *SendMessageToGroupChatRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type SendMessageToGroupChatResponse struct {
	MessageId            string   `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ChatId               string   `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	AuthorId             string   `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageToGroupChatResponse) Reset()         { *m = SendMessageToGroupChatResponse{} }
func (m *SendMessageToGroupChatResponse) String() string { return proto.CompactTextString(m) }
func (*SendMessageToGroupChatResponse) ProtoMessage()    {}
func (*SendMessageToGroupChatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52cf33cfe78713c, []int{17}
}

func (m *SendMessageToGroupChatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageToGroupChatResponse.Unmarshal(m, b)
}
func (m *SendMessageToGroupChatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageToGroupChatResponse.Marshal(b, m, deterministic)
}
func (m *SendMessageToGroupChatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageToGroupChatResponse.Merge(m, src)
}
func (m *SendMessageToGroupChatResponse) XXX_Size() int {
	return xxx_messageInfo_SendMessageToGroupChatResponse.Size(m)
}
func (m *SendMessageToGroupChatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageToGroupChatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageToGroupChatResponse proto.InternalMessageInfo

func (m *SendMessageToGroupChatResponse) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *SendMessageToGroupChatResponse) GetChatId() string {
	if m != nil {
		return m.ChatId
	}
	return ""
}

func (m *SendMessageToGroupChatResponse) GetAuthorId() string {
	if m != nil {
		return m.AuthorId
	}
	return ""
}

func (m *SendMessageToGroupChatResponse) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type GetContactsListRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContactsListRequest) Reset()         { *m = GetContactsListRequest{} }
func (m *GetContactsListRequest) String() string { return proto.CompactTextString(m) }
func (*GetContactsListRequest) ProtoMessage()    {}
func (*GetContactsListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52cf33cfe78713c, []int{18}
}

func (m *GetContactsListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContactsListRequest.Unmarshal(m, b)
}
func (m *GetContactsListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContactsListRequest.Marshal(b, m, deterministic)
}
func (m *GetContactsListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContactsListRequest.Merge(m, src)
}
func (m *GetContactsListRequest) XXX_Size() int {
	return xxx_messageInfo_GetContactsListRequest.Size(m)
}
func (m *GetContactsListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContactsListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetContactsListRequest proto.InternalMessageInfo

func (m *GetContactsListRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetContactsListResponse struct {
	UserId               string     `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Contacts             []*Contact `protobuf:"bytes,2,rep,name=contacts,proto3" json:"contacts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetContactsListResponse) Reset()         { *m = GetContactsListResponse{} }
func (m *GetContactsListResponse) String() string { return proto.CompactTextString(m) }
func (*GetContactsListResponse) ProtoMessage()    {}
func (*GetContactsListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52cf33cfe78713c, []int{19}
}

func (m *GetContactsListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContactsListResponse.Unmarshal(m, b)
}
func (m *GetContactsListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContactsListResponse.Marshal(b, m, deterministic)
}
func (m *GetContactsListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContactsListResponse.Merge(m, src)
}
func (m *GetContactsListResponse) XXX_Size() int {
	return xxx_messageInfo_GetContactsListResponse.Size(m)
}
func (m *GetContactsListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContactsListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetContactsListResponse proto.InternalMessageInfo

func (m *GetContactsListResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetContactsListResponse) GetContacts() []*Contact {
	if m != nil {
		return m.Contacts
	}
	return nil
}

type AddContactRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ContactId            string   `protobuf:"bytes,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddContactRequest) Reset()         { *m = AddContactRequest{} }
func (m *AddContactRequest) String() string { return proto.CompactTextString(m) }
func (*AddContactRequest) ProtoMessage()    {}
func (*AddContactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52cf33cfe78713c, []int{20}
}

func (m *AddContactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddContactRequest.Unmarshal(m, b)
}
func (m *AddContactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddContactRequest.Marshal(b, m, deterministic)
}
func (m *AddContactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddContactRequest.Merge(m, src)
}
func (m *AddContactRequest) XXX_Size() int {
	return xxx_messageInfo_AddContactRequest.Size(m)
}
func (m *AddContactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddContactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddContactRequest proto.InternalMessageInfo

func (m *AddContactRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AddContactRequest) GetContactId() string {
	if m != nil {
		return m.ContactId
	}
	return ""
}

type RemoveContactRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ContactId            string   `protobuf:"bytes,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveContactRequest) Reset()         { *m = RemoveContactRequest{} }
func (m *RemoveContactRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveContactRequest) ProtoMessage()    {}
func (*RemoveContactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52cf33cfe78713c, []int{21}
}

func (m *RemoveContactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveContactRequest.Unmarshal(m, b)
}
func (m *RemoveContactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveContactRequest.Marshal(b, m, deterministic)
}
func (m *RemoveContactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveContactRequest.Merge(m, src)
}
func (m *RemoveContactRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveContactRequest.Size(m)
}
func (m *RemoveContactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveContactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveContactRequest proto.InternalMessageInfo

func (m *RemoveContactRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RemoveContactRequest) GetContactId() string {
	if m != nil {
		return m.ContactId
	}
	return ""
}

func init() {
	proto.RegisterType((*Contact)(nil), "gopherchatter.v0.Contact")
	proto.RegisterType((*AuthenticateRequest)(nil), "gopherchatter.v0.AuthenticateRequest")
	proto.RegisterType((*AuthenticateResponse)(nil), "gopherchatter.v0.AuthenticateResponse")
	proto.RegisterType((*CreateUserRequest)(nil), "gopherchatter.v0.CreateUserRequest")
	proto.RegisterType((*CreateIndividualChatRequest)(nil), "gopherchatter.v0.CreateIndividualChatRequest")
	proto.RegisterType((*CreateIndividualChatResponse)(nil), "gopherchatter.v0.CreateIndividualChatResponse")
	proto.RegisterType((*GetIndividualChatsRequest)(nil), "gopherchatter.v0.GetIndividualChatsRequest")
	proto.RegisterType((*GetIndividualChatsResponse)(nil), "gopherchatter.v0.GetIndividualChatsResponse")
	proto.RegisterType((*CreateGroupChatRequest)(nil), "gopherchatter.v0.CreateGroupChatRequest")
	proto.RegisterType((*CreateGroupChatResponse)(nil), "gopherchatter.v0.CreateGroupChatResponse")
	proto.RegisterType((*GetGroupChatsRequest)(nil), "gopherchatter.v0.GetGroupChatsRequest")
	proto.RegisterType((*GetGroupChatsResponse)(nil), "gopherchatter.v0.GetGroupChatsResponse")
	proto.RegisterType((*AddContactToGroupChatRequest)(nil), "gopherchatter.v0.AddContactToGroupChatRequest")
	proto.RegisterType((*RemoveContactFromGroupChatRequest)(nil), "gopherchatter.v0.RemoveContactFromGroupChatRequest")
	proto.RegisterType((*SendMessageToIndividualChatRequest)(nil), "gopherchatter.v0.SendMessageToIndividualChatRequest")
	proto.RegisterType((*SendMessageToIndividualChatResponse)(nil), "gopherchatter.v0.SendMessageToIndividualChatResponse")
	proto.RegisterType((*SendMessageToGroupChatRequest)(nil), "gopherchatter.v0.SendMessageToGroupChatRequest")
	proto.RegisterType((*SendMessageToGroupChatResponse)(nil), "gopherchatter.v0.SendMessageToGroupChatResponse")
	proto.RegisterType((*GetContactsListRequest)(nil), "gopherchatter.v0.GetContactsListRequest")
	proto.RegisterType((*GetContactsListResponse)(nil), "gopherchatter.v0.GetContactsListResponse")
	proto.RegisterType((*AddContactRequest)(nil), "gopherchatter.v0.AddContactRequest")
	proto.RegisterType((*RemoveContactRequest)(nil), "gopherchatter.v0.RemoveContactRequest")
}

func init() { proto.RegisterFile("v0/gopherchatter.proto", fileDescriptor_f52cf33cfe78713c) }

var fileDescriptor_f52cf33cfe78713c = []byte{
	// 842 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0x5d, 0x4f, 0xdb, 0x4a,
	0x10, 0x55, 0x12, 0x2e, 0x49, 0xe6, 0x82, 0xb8, 0xec, 0x0d, 0x21, 0x38, 0x50, 0x51, 0xa3, 0x52,
	0xaa, 0xb6, 0x49, 0xca, 0xc7, 0x33, 0xa2, 0x51, 0x1b, 0x59, 0x14, 0x8a, 0x52, 0xe8, 0x43, 0xa5,
	0x8a, 0x9a, 0x78, 0x49, 0xac, 0x62, 0x6f, 0xb0, 0xd7, 0x41, 0x55, 0x7f, 0x01, 0x4f, 0x7d, 0xe9,
	0x4f, 0xea, 0x0f, 0xab, 0xd6, 0x5e, 0xe3, 0xd8, 0xde, 0x8d, 0xd3, 0x22, 0xb5, 0x8f, 0xbb, 0x9e,
	0x3d, 0x67, 0xf6, 0xcc, 0xcc, 0x1e, 0x43, 0x75, 0xd4, 0x6a, 0xf6, 0xc9, 0x70, 0x80, 0x9d, 0xde,
	0x40, 0xa7, 0x14, 0x3b, 0x8d, 0xa1, 0x43, 0x28, 0x41, 0xff, 0xc5, 0x37, 0x47, 0x2d, 0xa5, 0xde,
	0x27, 0xa4, 0x7f, 0x85, 0x9b, 0xfe, 0xf7, 0x0b, 0xef, 0xb2, 0x89, 0xad, 0x21, 0xfd, 0x12, 0x84,
	0xab, 0xfb, 0x50, 0x6c, 0x13, 0x9b, 0xea, 0x3d, 0x8a, 0x96, 0xa1, 0xe8, 0xb9, 0xd8, 0x39, 0x37,
	0x8d, 0x5a, 0x6e, 0x3d, 0xb7, 0x55, 0xee, 0xce, 0xb2, 0xa5, 0x66, 0xa0, 0x3a, 0x94, 0xfd, 0x0f,
	0xb6, 0x6e, 0xe1, 0x5a, 0xde, 0xff, 0x54, 0x62, 0x1b, 0xc7, 0xba, 0x85, 0xd5, 0x23, 0xf8, 0xff,
	0xc0, 0xa3, 0x03, 0x6c, 0x53, 0xb3, 0xa7, 0x53, 0xdc, 0xc5, 0xd7, 0x1e, 0x76, 0x29, 0x52, 0xc0,
	0x0f, 0xf1, 0x8f, 0xe4, 0xa2, 0x23, 0x6c, 0xcd, 0xbe, 0x0d, 0x75, 0xd7, 0xbd, 0x21, 0x8e, 0x11,
	0xc2, 0x85, 0x6b, 0x55, 0x87, 0x4a, 0x1c, 0xce, 0x1d, 0x12, 0xdb, 0xc5, 0xf2, 0xe4, 0xc6, 0x89,
	0xf2, 0x09, 0xa2, 0x0a, 0xfc, 0x43, 0xc9, 0x67, 0x6c, 0xd7, 0x0a, 0xfe, 0x87, 0x60, 0xa1, 0x1e,
	0xc2, 0x62, 0xdb, 0xc1, 0x3a, 0xc5, 0x67, 0x2e, 0x76, 0xee, 0x9b, 0xef, 0x3e, 0xd4, 0x03, 0x30,
	0xcd, 0x36, 0xcc, 0x91, 0x69, 0x78, 0xfa, 0x55, 0x7b, 0xa0, 0xd3, 0x10, 0x76, 0x1d, 0xe6, 0x6e,
	0x4c, 0x3a, 0x38, 0x8f, 0xe7, 0x0e, 0x6c, 0xef, 0xcc, 0xcf, 0x5f, 0x7d, 0x0f, 0xab, 0x62, 0x80,
	0xe8, 0xe2, 0xac, 0x96, 0x63, 0x17, 0x67, 0x4b, 0xcd, 0x40, 0x6b, 0x00, 0x16, 0xb6, 0x2e, 0x7c,
	0x5c, 0xb7, 0x96, 0x5f, 0x2f, 0x6c, 0x95, 0xbb, 0xe5, 0x60, 0x47, 0x33, 0x5c, 0x75, 0x17, 0x56,
	0x3a, 0x98, 0xc6, 0x41, 0xdd, 0x30, 0x2d, 0x99, 0x9a, 0xea, 0x09, 0x28, 0xa2, 0x53, 0x59, 0x45,
	0x58, 0x81, 0x12, 0x4f, 0x32, 0xcc, 0xa4, 0x18, 0x64, 0xe9, 0xaa, 0x27, 0x50, 0x0d, 0xee, 0xd7,
	0x71, 0x88, 0x37, 0x1c, 0xd7, 0xa6, 0x0e, 0x65, 0xff, 0xd0, 0xb8, 0xe6, 0x6c, 0x83, 0xb5, 0x15,
	0x43, 0xd4, 0x0d, 0xcb, 0xb4, 0x19, 0x57, 0xa0, 0x79, 0xd1, 0x5f, 0x6b, 0x86, 0x7a, 0x9b, 0x83,
	0xe5, 0x14, 0x64, 0x96, 0x5a, 0x31, 0xb2, 0xfc, 0x04, 0xb2, 0x42, 0x8c, 0x2c, 0xa1, 0xf2, 0x4c,
	0x52, 0xe5, 0x26, 0x54, 0x3a, 0x98, 0xde, 0xe5, 0x91, 0x2d, 0xf0, 0x21, 0x2c, 0x25, 0x0e, 0xdc,
	0x43, 0xdb, 0x6b, 0x58, 0x3d, 0x30, 0x0c, 0x3e, 0xbf, 0xa7, 0x24, 0xa5, 0xb0, 0x54, 0x0d, 0xb9,
	0xba, 0xec, 0xc2, 0xbd, 0x00, 0x30, 0x52, 0xa3, 0xcc, 0x77, 0x34, 0x43, 0x1d, 0xc1, 0xc3, 0x2e,
	0xb6, 0xc8, 0x08, 0x73, 0xd6, 0xd7, 0x0e, 0xb1, 0xfe, 0x04, 0x2f, 0x05, 0xf5, 0x1d, 0xb6, 0x8d,
	0x23, 0xec, 0xba, 0x7a, 0x1f, 0x9f, 0x12, 0xf1, 0xb8, 0x4d, 0x2a, 0xbf, 0xee, 0xd1, 0x01, 0x71,
	0x22, 0xe6, 0x52, 0xb0, 0xa1, 0x19, 0xa8, 0x06, 0x45, 0x46, 0x84, 0x6d, 0x1a, 0x56, 0x9f, 0x2f,
	0xd5, 0xef, 0x39, 0xd8, 0x98, 0x48, 0xcb, 0x8b, 0xe7, 0x77, 0x89, 0x1f, 0x12, 0x51, 0x97, 0xf9,
	0x8e, 0x66, 0x8c, 0xa7, 0x95, 0x97, 0xa7, 0x55, 0x90, 0xa7, 0x35, 0x13, 0x4f, 0x8b, 0xc0, 0x5a,
	0x2c, 0xab, 0xe9, 0x0b, 0xf0, 0x9b, 0x3a, 0x7c, 0xcb, 0xc1, 0x03, 0x19, 0xe3, 0xdf, 0x91, 0xe0,
	0x05, 0x54, 0x3b, 0x98, 0xf2, 0x26, 0x74, 0xdf, 0x98, 0x2e, 0xcd, 0x1c, 0x3d, 0x13, 0x96, 0x53,
	0x47, 0xb2, 0x86, 0x6f, 0x0f, 0x4a, 0xbc, 0x07, 0x83, 0xe1, 0xfb, 0x77, 0x7b, 0xa5, 0x91, 0x34,
	0xd8, 0x06, 0x87, 0xec, 0xde, 0x85, 0x32, 0x8b, 0x89, 0x06, 0x33, 0x2b, 0xb1, 0x44, 0xeb, 0xe7,
	0x93, 0xad, 0x7f, 0x0c, 0x95, 0xd8, 0xc8, 0xdd, 0x13, 0x6f, 0xfb, 0x07, 0xc0, 0x7c, 0xc7, 0xbf,
	0x43, 0x3b, 0xb8, 0x03, 0xfa, 0x08, 0x73, 0xe3, 0xa6, 0x8b, 0x1e, 0xa5, 0xef, 0x28, 0xf0, 0x78,
	0x65, 0x33, 0x2b, 0x8c, 0xab, 0xab, 0x01, 0x44, 0x86, 0x8b, 0x36, 0x04, 0x02, 0x26, 0xed, 0x58,
	0xa9, 0x36, 0x82, 0x9f, 0x96, 0x46, 0xf8, 0xd3, 0xd2, 0x78, 0xc5, 0x7e, 0x5a, 0x90, 0x07, 0x15,
	0x91, 0x5b, 0xa2, 0xe7, 0x32, 0x50, 0xe1, 0x3b, 0xa1, 0x34, 0xa6, 0x0d, 0xe7, 0x37, 0xb8, 0x84,
	0x85, 0x84, 0xe3, 0xa0, 0x2d, 0x19, 0x44, 0x72, 0x18, 0x95, 0x27, 0x53, 0x44, 0x72, 0x1e, 0x02,
	0x28, 0x6d, 0xbf, 0xe8, 0x69, 0x1a, 0x40, 0x6a, 0xed, 0xca, 0xb3, 0xe9, 0x82, 0x39, 0xe1, 0x27,
	0x98, 0x8f, 0xd9, 0x11, 0xda, 0x14, 0x1e, 0x4f, 0x19, 0x9c, 0xf2, 0x38, 0x33, 0x8e, 0x33, 0x9c,
	0xc3, 0x92, 0xd0, 0xa3, 0x90, 0xa0, 0x06, 0x93, 0xcc, 0x4c, 0xda, 0x12, 0x26, 0x28, 0x72, 0x47,
	0x42, 0x3b, 0x69, 0x96, 0x4c, 0xff, 0x92, 0x52, 0xdd, 0xe6, 0x40, 0x11, 0xd8, 0x41, 0xd8, 0x84,
	0xbb, 0x69, 0xae, 0x6c, 0xcf, 0x52, 0xf6, 0x7e, 0xf1, 0x14, 0xd7, 0xf5, 0x2b, 0x54, 0xc5, 0x2f,
	0x32, 0x6a, 0x66, 0x00, 0xa6, 0xae, 0xdb, 0x9a, 0xfe, 0x40, 0x34, 0x0f, 0x89, 0xa7, 0x54, 0x34,
	0x0f, 0xe2, 0x07, 0x5a, 0x34, 0x0f, 0xb2, 0x77, 0x59, 0x03, 0x88, 0x7a, 0x42, 0xf4, 0x72, 0xa4,
	0x5e, 0x59, 0x69, 0xed, 0xde, 0xc2, 0x7c, 0xac, 0xf0, 0xa2, 0x4e, 0x17, 0x3d, 0xb3, 0x32, 0xc0,
	0x97, 0x8b, 0x1f, 0x16, 0x62, 0x00, 0xa3, 0xd6, 0xc5, 0xac, 0x1f, 0xb2, 0xf3, 0x33, 0x00, 0x00,
	0xff, 0xff, 0xdf, 0xab, 0x22, 0xb5, 0x9c, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GopherChatterClient is the client API for GopherChatter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GopherChatterClient interface {
	Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	CreateIndividualChat(ctx context.Context, in *CreateIndividualChatRequest, opts ...grpc.CallOption) (*CreateIndividualChatResponse, error)
	CreateGroupChat(ctx context.Context, in *CreateGroupChatRequest, opts ...grpc.CallOption) (*CreateGroupChatResponse, error)
	GetIndividualChats(ctx context.Context, in *GetIndividualChatsRequest, opts ...grpc.CallOption) (*GetIndividualChatsResponse, error)
	GetGroupChats(ctx context.Context, in *GetGroupChatsRequest, opts ...grpc.CallOption) (*GetGroupChatsResponse, error)
	AddContactToGroupChat(ctx context.Context, in *AddContactToGroupChatRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	RemoveContactFromGroupChat(ctx context.Context, in *RemoveContactFromGroupChatRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	SendMessageToIndiviualChat(ctx context.Context, in *SendMessageToIndividualChatRequest, opts ...grpc.CallOption) (*SendMessageToIndividualChatResponse, error)
	SendMessageToGroupChat(ctx context.Context, in *SendMessageToGroupChatRequest, opts ...grpc.CallOption) (*SendMessageToGroupChatResponse, error)
	GetContactsList(ctx context.Context, in *GetContactsListRequest, opts ...grpc.CallOption) (*GetContactsListResponse, error)
	AddContact(ctx context.Context, in *AddContactRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	RemoveContact(ctx context.Context, in *RemoveContactRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type gopherChatterClient struct {
	cc *grpc.ClientConn
}

func NewGopherChatterClient(cc *grpc.ClientConn) GopherChatterClient {
	return &gopherChatterClient{cc}
}

func (c *gopherChatterClient) Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	out := new(AuthenticateResponse)
	err := c.cc.Invoke(ctx, "/gopherchatter.v0.GopherChatter/Authenticate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopherChatterClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/gopherchatter.v0.GopherChatter/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopherChatterClient) CreateIndividualChat(ctx context.Context, in *CreateIndividualChatRequest, opts ...grpc.CallOption) (*CreateIndividualChatResponse, error) {
	out := new(CreateIndividualChatResponse)
	err := c.cc.Invoke(ctx, "/gopherchatter.v0.GopherChatter/CreateIndividualChat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopherChatterClient) CreateGroupChat(ctx context.Context, in *CreateGroupChatRequest, opts ...grpc.CallOption) (*CreateGroupChatResponse, error) {
	out := new(CreateGroupChatResponse)
	err := c.cc.Invoke(ctx, "/gopherchatter.v0.GopherChatter/CreateGroupChat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopherChatterClient) GetIndividualChats(ctx context.Context, in *GetIndividualChatsRequest, opts ...grpc.CallOption) (*GetIndividualChatsResponse, error) {
	out := new(GetIndividualChatsResponse)
	err := c.cc.Invoke(ctx, "/gopherchatter.v0.GopherChatter/GetIndividualChats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopherChatterClient) GetGroupChats(ctx context.Context, in *GetGroupChatsRequest, opts ...grpc.CallOption) (*GetGroupChatsResponse, error) {
	out := new(GetGroupChatsResponse)
	err := c.cc.Invoke(ctx, "/gopherchatter.v0.GopherChatter/GetGroupChats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopherChatterClient) AddContactToGroupChat(ctx context.Context, in *AddContactToGroupChatRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/gopherchatter.v0.GopherChatter/AddContactToGroupChat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopherChatterClient) RemoveContactFromGroupChat(ctx context.Context, in *RemoveContactFromGroupChatRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/gopherchatter.v0.GopherChatter/RemoveContactFromGroupChat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopherChatterClient) SendMessageToIndiviualChat(ctx context.Context, in *SendMessageToIndividualChatRequest, opts ...grpc.CallOption) (*SendMessageToIndividualChatResponse, error) {
	out := new(SendMessageToIndividualChatResponse)
	err := c.cc.Invoke(ctx, "/gopherchatter.v0.GopherChatter/SendMessageToIndiviualChat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopherChatterClient) SendMessageToGroupChat(ctx context.Context, in *SendMessageToGroupChatRequest, opts ...grpc.CallOption) (*SendMessageToGroupChatResponse, error) {
	out := new(SendMessageToGroupChatResponse)
	err := c.cc.Invoke(ctx, "/gopherchatter.v0.GopherChatter/SendMessageToGroupChat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopherChatterClient) GetContactsList(ctx context.Context, in *GetContactsListRequest, opts ...grpc.CallOption) (*GetContactsListResponse, error) {
	out := new(GetContactsListResponse)
	err := c.cc.Invoke(ctx, "/gopherchatter.v0.GopherChatter/GetContactsList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopherChatterClient) AddContact(ctx context.Context, in *AddContactRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/gopherchatter.v0.GopherChatter/AddContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopherChatterClient) RemoveContact(ctx context.Context, in *RemoveContactRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/gopherchatter.v0.GopherChatter/RemoveContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GopherChatterServer is the server API for GopherChatter service.
type GopherChatterServer interface {
	Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error)
	CreateUser(context.Context, *CreateUserRequest) (*empty.Empty, error)
	CreateIndividualChat(context.Context, *CreateIndividualChatRequest) (*CreateIndividualChatResponse, error)
	CreateGroupChat(context.Context, *CreateGroupChatRequest) (*CreateGroupChatResponse, error)
	GetIndividualChats(context.Context, *GetIndividualChatsRequest) (*GetIndividualChatsResponse, error)
	GetGroupChats(context.Context, *GetGroupChatsRequest) (*GetGroupChatsResponse, error)
	AddContactToGroupChat(context.Context, *AddContactToGroupChatRequest) (*empty.Empty, error)
	RemoveContactFromGroupChat(context.Context, *RemoveContactFromGroupChatRequest) (*empty.Empty, error)
	SendMessageToIndiviualChat(context.Context, *SendMessageToIndividualChatRequest) (*SendMessageToIndividualChatResponse, error)
	SendMessageToGroupChat(context.Context, *SendMessageToGroupChatRequest) (*SendMessageToGroupChatResponse, error)
	GetContactsList(context.Context, *GetContactsListRequest) (*GetContactsListResponse, error)
	AddContact(context.Context, *AddContactRequest) (*empty.Empty, error)
	RemoveContact(context.Context, *RemoveContactRequest) (*empty.Empty, error)
}

// UnimplementedGopherChatterServer can be embedded to have forward compatible implementations.
type UnimplementedGopherChatterServer struct {
}

func (*UnimplementedGopherChatterServer) Authenticate(ctx context.Context, req *AuthenticateRequest) (*AuthenticateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}
func (*UnimplementedGopherChatterServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedGopherChatterServer) CreateIndividualChat(ctx context.Context, req *CreateIndividualChatRequest) (*CreateIndividualChatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateIndividualChat not implemented")
}
func (*UnimplementedGopherChatterServer) CreateGroupChat(ctx context.Context, req *CreateGroupChatRequest) (*CreateGroupChatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGroupChat not implemented")
}
func (*UnimplementedGopherChatterServer) GetIndividualChats(ctx context.Context, req *GetIndividualChatsRequest) (*GetIndividualChatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIndividualChats not implemented")
}
func (*UnimplementedGopherChatterServer) GetGroupChats(ctx context.Context, req *GetGroupChatsRequest) (*GetGroupChatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroupChats not implemented")
}
func (*UnimplementedGopherChatterServer) AddContactToGroupChat(ctx context.Context, req *AddContactToGroupChatRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddContactToGroupChat not implemented")
}
func (*UnimplementedGopherChatterServer) RemoveContactFromGroupChat(ctx context.Context, req *RemoveContactFromGroupChatRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveContactFromGroupChat not implemented")
}
func (*UnimplementedGopherChatterServer) SendMessageToIndiviualChat(ctx context.Context, req *SendMessageToIndividualChatRequest) (*SendMessageToIndividualChatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessageToIndiviualChat not implemented")
}
func (*UnimplementedGopherChatterServer) SendMessageToGroupChat(ctx context.Context, req *SendMessageToGroupChatRequest) (*SendMessageToGroupChatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessageToGroupChat not implemented")
}
func (*UnimplementedGopherChatterServer) GetContactsList(ctx context.Context, req *GetContactsListRequest) (*GetContactsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContactsList not implemented")
}
func (*UnimplementedGopherChatterServer) AddContact(ctx context.Context, req *AddContactRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddContact not implemented")
}
func (*UnimplementedGopherChatterServer) RemoveContact(ctx context.Context, req *RemoveContactRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveContact not implemented")
}

func RegisterGopherChatterServer(s *grpc.Server, srv GopherChatterServer) {
	s.RegisterService(&_GopherChatter_serviceDesc, srv)
}

func _GopherChatter_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopherChatterServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopherchatter.v0.GopherChatter/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopherChatterServer).Authenticate(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopherChatter_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopherChatterServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopherchatter.v0.GopherChatter/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopherChatterServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopherChatter_CreateIndividualChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIndividualChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopherChatterServer).CreateIndividualChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopherchatter.v0.GopherChatter/CreateIndividualChat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopherChatterServer).CreateIndividualChat(ctx, req.(*CreateIndividualChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopherChatter_CreateGroupChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopherChatterServer).CreateGroupChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopherchatter.v0.GopherChatter/CreateGroupChat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopherChatterServer).CreateGroupChat(ctx, req.(*CreateGroupChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopherChatter_GetIndividualChats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIndividualChatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopherChatterServer).GetIndividualChats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopherchatter.v0.GopherChatter/GetIndividualChats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopherChatterServer).GetIndividualChats(ctx, req.(*GetIndividualChatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopherChatter_GetGroupChats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupChatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopherChatterServer).GetGroupChats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopherchatter.v0.GopherChatter/GetGroupChats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopherChatterServer).GetGroupChats(ctx, req.(*GetGroupChatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopherChatter_AddContactToGroupChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddContactToGroupChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopherChatterServer).AddContactToGroupChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopherchatter.v0.GopherChatter/AddContactToGroupChat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopherChatterServer).AddContactToGroupChat(ctx, req.(*AddContactToGroupChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopherChatter_RemoveContactFromGroupChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveContactFromGroupChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopherChatterServer).RemoveContactFromGroupChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopherchatter.v0.GopherChatter/RemoveContactFromGroupChat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopherChatterServer).RemoveContactFromGroupChat(ctx, req.(*RemoveContactFromGroupChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopherChatter_SendMessageToIndiviualChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageToIndividualChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopherChatterServer).SendMessageToIndiviualChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopherchatter.v0.GopherChatter/SendMessageToIndiviualChat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopherChatterServer).SendMessageToIndiviualChat(ctx, req.(*SendMessageToIndividualChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopherChatter_SendMessageToGroupChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageToGroupChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopherChatterServer).SendMessageToGroupChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopherchatter.v0.GopherChatter/SendMessageToGroupChat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopherChatterServer).SendMessageToGroupChat(ctx, req.(*SendMessageToGroupChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopherChatter_GetContactsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContactsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopherChatterServer).GetContactsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopherchatter.v0.GopherChatter/GetContactsList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopherChatterServer).GetContactsList(ctx, req.(*GetContactsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopherChatter_AddContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopherChatterServer).AddContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopherchatter.v0.GopherChatter/AddContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopherChatterServer).AddContact(ctx, req.(*AddContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopherChatter_RemoveContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopherChatterServer).RemoveContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopherchatter.v0.GopherChatter/RemoveContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopherChatterServer).RemoveContact(ctx, req.(*RemoveContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GopherChatter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gopherchatter.v0.GopherChatter",
	HandlerType: (*GopherChatterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _GopherChatter_Authenticate_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _GopherChatter_CreateUser_Handler,
		},
		{
			MethodName: "CreateIndividualChat",
			Handler:    _GopherChatter_CreateIndividualChat_Handler,
		},
		{
			MethodName: "CreateGroupChat",
			Handler:    _GopherChatter_CreateGroupChat_Handler,
		},
		{
			MethodName: "GetIndividualChats",
			Handler:    _GopherChatter_GetIndividualChats_Handler,
		},
		{
			MethodName: "GetGroupChats",
			Handler:    _GopherChatter_GetGroupChats_Handler,
		},
		{
			MethodName: "AddContactToGroupChat",
			Handler:    _GopherChatter_AddContactToGroupChat_Handler,
		},
		{
			MethodName: "RemoveContactFromGroupChat",
			Handler:    _GopherChatter_RemoveContactFromGroupChat_Handler,
		},
		{
			MethodName: "SendMessageToIndiviualChat",
			Handler:    _GopherChatter_SendMessageToIndiviualChat_Handler,
		},
		{
			MethodName: "SendMessageToGroupChat",
			Handler:    _GopherChatter_SendMessageToGroupChat_Handler,
		},
		{
			MethodName: "GetContactsList",
			Handler:    _GopherChatter_GetContactsList_Handler,
		},
		{
			MethodName: "AddContact",
			Handler:    _GopherChatter_AddContact_Handler,
		},
		{
			MethodName: "RemoveContact",
			Handler:    _GopherChatter_RemoveContact_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v0/gopherchatter.proto",
}
